using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConsoleApp3
{
    internal class Program
    {
        static void Main(string[] args)
        {
            bool a1 = true;
            Console.WriteLine(a1);
            bool a2 = true;
            Console.WriteLine(a2);
            bool a3 = true;
            Console.WriteLine(a3);
            bool a4 = true;
            Console.WriteLine(a4);
            bool a5 = true;
            Console.WriteLine(a5);

            bool a6 = false;
            Console.WriteLine(a6);
            bool a7 = false;
            Console.WriteLine(a7);
            bool a8 = false;
            Console.WriteLine(a8);
            bool a9 = false;
            Console.WriteLine(a9);
            bool a10 = false;
            Console.WriteLine(a10);

            byte b1 = 1;
            byte b2 = 2;
            byte b3 = 3;
            byte b4 = 4;
            byte b5 = 5;
            byte b6 = 6;
            byte b7 = 7;
            byte b8 = 8;
            byte b9 = 9;
            byte b10 = 10;
            Console.WriteLine(b1);
            Console.WriteLine(b2);
            Console.WriteLine(b3);
            Console.WriteLine(b4);
            Console.WriteLine(b5);
            Console.WriteLine(b6);
            Console.WriteLine(b7);
            Console.WriteLine(b8);
            Console.WriteLine(b9);
            Console.WriteLine(b10);

            sbyte q1 = 1;
            sbyte q2 = 2;
            sbyte q3 = 3;
            sbyte q4 = 4;
            sbyte q5 = 5;
            sbyte q6 = 6;
            sbyte q7 = 7;
            sbyte q8 = 8;
            sbyte q9 = 9;
            sbyte q10 = 10;
            Console.WriteLine(q1);
            Console.WriteLine(q2);
            Console.WriteLine(q3);
            Console.WriteLine(q4);
            Console.WriteLine(q5);
            Console.WriteLine(q6);
            Console.WriteLine(q7);
            Console.WriteLine(q8);
            Console.WriteLine(q9);
            Console.WriteLine(q10);

            char c1 = 'a';
            char c2 = 'a';
            char c3 = 'a';
            char c4 = 'a';
            char c5 = 'a';
            char c6 = 'a';
            char c7 = 'a';
            char c8 = 'a';
            char c9 = 'a';
            char c10 = 'a';
            Console.WriteLine(c1);
            Console.WriteLine(c2);
            Console.WriteLine(c3);
            Console.WriteLine(c4);
            Console.WriteLine(c5);
            Console.WriteLine(c6);
            Console.WriteLine(c7);
            Console.WriteLine(c8);
            Console.WriteLine(c9);
            Console.WriteLine(c10);

            decimal d1 = 1;
            decimal d2 = 1;
            decimal d3 = 1;
            decimal d4 = 1;
            decimal d5 = 1;
            decimal d6 = 1;
            decimal d7 = 1;
            decimal d8 = 1;
            decimal d9 = 1;
            decimal d10 = 1;
            Console.WriteLine(d1);
            Console.WriteLine(d2);
            Console.WriteLine(d3);
            Console.WriteLine(d4);
            Console.WriteLine(d5);
            Console.WriteLine(d6);
            Console.WriteLine(d7);
            Console.WriteLine(d8);
            Console.WriteLine(d9);
            Console.WriteLine(d10);

            double r1 = 1.1;
            double r2 = 1.1;
            double r3 = 1.1;
            double r4 = 1.1;
            double r5 = 1.1;
            double r6 = 1.1;
            double r7 = 1.1;
            double r8 = 1.1;
            double r9 = 1.1;
            double r10 = 1.1;
            Console.WriteLine(r1);
            Console.WriteLine(r2);
            Console.WriteLine(r3);
            Console.WriteLine(r4);
            Console.WriteLine(r5);
            Console.WriteLine(r6);
            Console.WriteLine(r7);
            Console.WriteLine(r8);
            Console.WriteLine(r9);
            Console.WriteLine(r10);

            float f1 = 1.3f;
            float f2 = 1.3f;
            float f3 = 1.3f;
            float f4 = 1.3f;
            float f5 = 1.3f;
            float f6 = 1.3f;
            float f7 = 1.3f;
            float f8 = 1.3f;
            float f9 = 1.3f;
            float f10 = 1.3f;

            Console.WriteLine(f1);
            Console.WriteLine(f2);
            Console.WriteLine(f3);
            Console.WriteLine(f4);
            Console.WriteLine(f5);
            Console.WriteLine(f6);
            Console.WriteLine(f7);
            Console.WriteLine(f8);
            Console.WriteLine(f9);
            Console.WriteLine(f10);

            int i1 = 1;
            int i2 = 2;
            int i3 = 3;
            int i4 = 4;
            int i5 = 5;
            int i6 = 6;
            int i7 = 7;
            int i8 = 8;
            int i9 = 9;
            int i10 = 9;
            Console.WriteLine(i1);
            Console.WriteLine(i2);
            Console.WriteLine(i3);
            Console.WriteLine(i4);
            Console.WriteLine(i5);
            Console.WriteLine(i6);
            Console.WriteLine(i7);
            Console.WriteLine(i8);
            Console.WriteLine(i9);
            Console.WriteLine(i10);

            uint u1 = 1;
            uint u2 = 2;
            uint u3 = 3;
            uint u4 = 4;
            uint u5 = 5;
            uint u6 = 6;
            uint u7 = 7;
            uint u8 = 8;
            uint u9 = 9;
            uint u10 = 9;
            Console.WriteLine(u1);
            Console.WriteLine(u2);
            Console.WriteLine(u3);
            Console.WriteLine(u4);
            Console.WriteLine(u5);
            Console.WriteLine(u6);
            Console.WriteLine(u7);
            Console.WriteLine(u8);
            Console.WriteLine(u9);
            Console.WriteLine(u10);

            long l1 = 1;
            long l2 = 2;
            long l3 = 3;
            long l4 = 4;
            long l5 = 5;
            long l6 = 6;
            long l7 = 7;
            long l8 = 8;
            long l9 = 9;
            long l10 = 9;
            Console.WriteLine(l1);
            Console.WriteLine(l2);
            Console.WriteLine(l3);
            Console.WriteLine(l4);
            Console.WriteLine(l5);
            Console.WriteLine(l6);
            Console.WriteLine(l7);
            Console.WriteLine(l8);
            Console.WriteLine(l9);
            Console.WriteLine(l10);

            ulong h1 = 1;
            ulong h2 = 2;
            ulong h3 = 3;
            ulong h4 = 4;
            ulong h5 = 5;
            ulong h6 = 6;
            ulong h7 = 7;
            ulong h8 = 8;
            ulong h9 = 9;
            ulong h10 = 9;
            Console.WriteLine(h1);
            Console.WriteLine(h2);
            Console.WriteLine(h3);
            Console.WriteLine(h4);
            Console.WriteLine(h5);
            Console.WriteLine(h6);
            Console.WriteLine(h7);
            Console.WriteLine(h8);
            Console.WriteLine(h9);
            Console.WriteLine(h10);

            object o1 = 1;
            object o2 = 2;
            object o3 = 3;
            object o4 = 4;
            object o5 = 5;
            object o6 = 6;
            object o7 = 7;
            object o8 = 8;
            object o9 = 9;
            object o10 = 10;
            Console.WriteLine(o1);
            Console.WriteLine(o2);
            Console.WriteLine(o3);
            Console.WriteLine(o4);
            Console.WriteLine(o5);
            Console.WriteLine(o6);
            Console.WriteLine(o7);
            Console.WriteLine(o8);
            Console.WriteLine(o9);
            Console.WriteLine(o10);

            short s1 = 1;
            short s2 = 1;
            short s3 = 1;
            short s4 = 1;
            short s5 = 1;
            short s6 = 1;
            short s7 = 1;
            short s8 = 1;
            short s9 = 1;
            short s10 = 1;
            Console.WriteLine(s1);
            Console.WriteLine(s2);
            Console.WriteLine(s3);
            Console.WriteLine(s4);
            Console.WriteLine(s5);
            Console.WriteLine(s6);
            Console.WriteLine(s7);
            Console.WriteLine(s8);
            Console.WriteLine(s9);
            Console.WriteLine(s10);

            ushort m1 = 1;
            ushort m2 = 1;
            ushort m3 = 1;
            ushort m4 = 1;
            ushort m5 = 1;
            ushort m6 = 1;
            ushort m7 = 1;
            ushort m8 = 1;
            ushort m9 = 1;
            ushort m10 = 1;
            Console.WriteLine(m1);
            Console.WriteLine(m2);
            Console.WriteLine(m3);
            Console.WriteLine(m4);
            Console.WriteLine(m5);
            Console.WriteLine(m6);
            Console.WriteLine(m7);
            Console.WriteLine(m8);
            Console.WriteLine(m9);
            Console.WriteLine(m10);

            string str1 = "das";
            string str2 = "das";
            string str3 = "das";
            string str4 = "das";
            string str5 = "das";
            string str6 = "das";
            string str7 = "das";
            string str8 = "das";
            string str9 = "das";
            string str10 = "das";
            Console.WriteLine(str1);
            Console.WriteLine(str2);
            Console.WriteLine(str3);
            Console.WriteLine(str4);
            Console.WriteLine(str5);
            Console.WriteLine(str6);
            Console.WriteLine(str7);
            Console.WriteLine(str8);
            Console.WriteLine(str9);
            Console.WriteLine(str10);



            Console.ReadKey();
        }
    }
}